### ISSUE TITLE
Reading the results

### ISSUE THREAD

**Issue by tassiaheuser** [LuChang-CS/MTGAN#2]
Hello,
I ran the code with MIMIC-4.
As result I got a npz file with some files x (a 3d array containing 0s and 1s) and lens. 
How do I understand the results?

Thank you in advance!

**Comment by LuChang-CS** [comment]
Hi, if you run the `run_generate.py`, you can refer to the [line 68](https://github.com/LuChang-CS/MTGAN/blob/main/run_generate.py#L68)
```python
np.savez_compressed(synthetic_path, x=fake_x, lens=fake_lens)
```

The generated file contains `x` and `lens`. `x: (n, T, d)` means binary diseases in EHR data. `n` is the number of patients. `T` is the max visit number. `d` is the number of diseases. `lens: (n, )` is the number of visits of each patient.

**Comment by tassiaheuser** [comment]
Hi, thank you for your answer. This helps a lot!
